### ISSUE TITLE
Commands from operationId

### ISSUE THREAD

**Issue by ServerlessArchitect** [danielgtaylor/restish#127]
Restish generates convenient command names such as "messaging-email-address-status-get".

However, our OpenAPI spec defines operationId for all the operations. Is it possible to have Restish use those instead?

**Comment by danielgtaylor** [comment]
@ServerlessArchitect the name should be getting set from the operation ID, via this code: https://github.com/danielgtaylor/restish/blob/main/openapi/openapi.go#L214

Do you have a short example which exhibits the incorrect behavior that I could debug?

**Comment by danielgtaylor** [comment]
@ServerlessArchitect 

> Just to confirm, are you saying the command names are still based on my operationIds, just normalised?

Yes, it is based on the `operationId` if present. It is also possible to [override it via `x-cli-name`](https://rest.sh/#/openapi?id=name).
