### ISSUE TITLE
base url in configuration and openapi discovery.

### ISSUE THREAD

**Issue by r4um** [danielgtaylor/restish#148]
Even if a path is specified in the base URL, e.g.

```
"base": "http://myexample.com/api/v1/"
``` 

The API discovery never uses the path added in the URL , the `/api/v1/`. We have the `openapi.json` endpoint at `/api/v1/openapi.json`.

Should it be honoring the extra path in the base URL while doing discovery? If yes, happy to raise a PR.

**Comment by danielgtaylor** [comment]
I believe this was fixed with #146
