### ISSUE TITLE
openapi: avoid adding non required parameters with no default value

### ISSUE THREAD

**Issue by asaf** [danielgtaylor/restish#19]
Hey,

I have an openapi endpoint with some _non required_ query parameters with no default value set in spec.

Restish sets these implicitly. I suggest avoiding this as it puts empty values which may not always work well.

Thanks.

**Comment by benjumanji** [comment]
dup of #9 ?

**Comment by asaf** [comment]
@benjumanji seems like that, I fetched from master and it's still happening though.

**Comment by danielgtaylor** [comment]
Can we confirm whether this is still happening with the 0.5.0 release? It would be great to get an example OpenAPI snippet that exhibits this behavior if so, then I can repro and fix.

**Comment by danielgtaylor** [comment]
Closing as I believe this is fixed, if not please reopen with an example!
