### ISSUE TITLE
Remote references in open api spec documents are not supported

### ISSUE THREAD

**Issue by zak905** [danielgtaylor/restish#203]
When an open api spec document contains a remote reference like:
```
 requestBody:
        $ref: "https://some-url.com/openapi.yml#/paths/~1object/post/requestBody"
```

restish fails to load the api and returns errors like `Caught error: errors [cannot resolve reference`

This supported by https://github.com/pb33f/libopenapi and is controlled by a flag named `AllowRemoteLookup`, more details on  #202

**Comment by danielgtaylor** [comment]
Merged in #211
