### ISSUE TITLE
make operations more readable

### ISSUE THREAD

**Issue by jrhizor** [danielgtaylor/restish#29]
Operation names in OpenAPI specs are commonly camelcase. Currently (as shown in https://github.com/danielgtaylor/restish/blob/main/openapi/openapi_test.go) an operation like `createPets` turns into `createpets` in the CLI. It seems like it'd be generally better if this turned into `create-pets` instead. In the actual API I'm starting to use Restish for, there are operations like `getsourcedefinitionspecification` which would be significantly more readable as `get-source-definition-specification`.

While it's possible to add `x-cli-name` for each operation, this is really annoying for an API with a lot of endpoints. 

Can we instead add `ToKebab` from https://github.com/iancoleman/strcase before `slug.Make` by default? If you're concerned about backwards compatibility, we might need a project-specific config option for `~/.restish/apis.json`.

If this sounds good I'd be happy to submit a PR.

**Comment by danielgtaylor** [comment]
I've updated this to better handle camel and other casing schemes, and made it backward compatible via the use of command aliases, see https://github.com/danielgtaylor/restish/commit/4aa30c3f866cf4a551c64ea3d4c6eefea72cf2bc.

**Comment by jrhizor** [comment]
Thanks!
