### ISSUE TITLE
Trouble with Restish post syntax for arrays

### ISSUE THREAD

**Issue by kpayson** [danielgtaylor/restish#33]
I'm having trouble with the Restish syntax with arrays in the post params.

This is what my command looks like:

`restish a-ci email-controller-send-email 1 from: "me@gmail.com",  subject: "Restish is Great", html: "Wow", to[]:"you@labshare.org" `

I get the error:  no matches found: to[]:you@labshare.org

How do I create this post body
 {
  from:'me@gmail.com',
  to:['you@gmail.com']
 subject:'Restish is Great'
html:'Wow'
}

note: the 'to' field needs to be an array since that is the way it is described in the schema for the email object

      `"to": {
          "type": "array",
          "items": {
              "type": "string",
              "format": "idn-email"
          }
      },`

**Comment by danielgtaylor** [comment]
@kpayson looks like your shell may be trying to interpret the `[]`. You can quote it like this (and the double quotes aren't required either):

```sh
restish a-ci email-controller-send-email 1 'from: me@gmail.com, subject: Restish is Great, html: Wow, to[]: you@labshare.org'
```

If you have any other issues with the shorthand syntax you can always use stdin instead with plain JSON, like:

```sh
// Assuming `body.json` contains the JSON body you want to send
restish a-ci email-controller-send-email 1 <body.json
```

**Comment by kpayson** [comment]
Thanks.  The techniques of putting single quotes around the entire post body worked.  FYI my shell is zsh
