### ISSUE TITLE
setting Authorization header to avoid authentication redirect

### ISSUE THREAD

**Issue by kpayson** [danielgtaylor/restish#35]
I thought I could provide the bearer token myself using the -H flag to avoid getting prompted to authenticate but it doesn't seem to work

If there is nothing in the cache file, when I run my command, I am still prompted to login
ex

`restish local users-list 1 -H "Authorization: bearer eyJhbGciOiJSUzI1NiIsInR..."`

am I doing something wrong?  I have a token.  How can I use it to avoid being prompted to authenticate

**Comment by danielgtaylor** [comment]
Short-term you can save the token into the cache file manually. Longer term we need to fix this bug and only prompt if it isn't already given.

**Comment by danielgtaylor** [comment]
@kpayson I made a quick fix for this issue. Please try again.
