### ISSUE TITLE
inconsistent usage of flags

### ISSUE THREAD

**Issue by myrho** [danielgtaylor/restish#48]
Running restish against `https://petstore3.swagger.io/api/v3/openapi.json` gives me the following endpoint usage message:

```
Usage:
  restish petstore find-pets-by-status [flags]

Aliases:
  find-pets-by-status, findpetsbystatus

Flags:
  -h, --help            help for find-pets-by-status
      --status string   Status values that need to be considered for filter (default "available")

```

Running `restish petstore findpetsbystatus --status available` yields

```
HTTP/2.0 400 Bad Request
```

while `restish petstore findpetsbystatus -q status=available` yields the expected response.

So the flag `--status` seems not to work as expected as described in the usage message.

But it works with `restish petstore findpetsbytags --tags animal` although it has a similar usage:

```
Usage:
  restish petstore findpetsbytags [flags]

Flags:
  -h, --help           help for findpetsbytags
      --tags strings   Tags to filter by
```

**Comment by danielgtaylor** [comment]
The sample OpenAPI specifies the default is `available` and says the param is not required, so Restish recognizes the default and sends nothing. IMO this is working as designed and if the API requires the param then it should specify so in the OpenAPI.

**Comment by myrho** [comment]
Ok, I see. The request works with other status than `available`. So I'd expect that omitting the status parameter, ie. `restish petstore findpetsbystatus`, would yield the `available` pets by default. But this also yields a `Bad Request` error.

**Comment by danielgtaylor** [comment]
@myrho I thought about this some more and it didn't sit well with me. I do think the API example you gave is just broken/wrong (it makes no sense to have a required argument with a default), but I did rethink how parameters are getting sent (or not) in Restish. Take a look at https://github.com/danielgtaylor/restish/pull/96, which changes things so any explicitly passed argument on the command line will result in that value being sent over the wire, regardless of what the default may be.

**Comment by myrho** [comment]
Yes, you are right, a default should be ignored on a required argument so the user is forced to pass a value explicitly. However, in the example spec `status` is **not** required
```json
"get": {
    "tags": [
      "pet"
    ],
    "summary": "Finds Pets by status",
    "description": "Multiple status values can be provided with comma separated strings",
    "operationId": "findPetsByStatus",
    "parameters": [
      {
        "name": "status",
        "in": "query",
        "description": "Status values that need to be considered for filter",
        "required": false,
        "explode": true,
        "schema": {
          "type": "string",
          "default": "available",
          "enum": [
            "available",
            "pending",
            "sold"
          ]
        }
      }
    ],

}
```

and still `restish petstore findpetsbystatus` responds with 

```
HTTP/2.0 400 Bad Request
...

No status provided. Try again?
```

Am I getting something wrong with your fix? Shouldn't `status` be `available` by default?

**Comment by danielgtaylor** [comment]
@myrho this doesn't appear to be well-defined in the OpenAPI spec. It says the default can be any value and provides no guidance how clients should handle it. Here's my interpretation: it documents the default value that the server uses, therefore clients have no need for it other than as documentation. Do you know of any place that says clients should send this value instead?

**Comment by myrho** [comment]
I totally agree. The default value is not for the client to set. 

The issue I'm having is this: Restish **requires** a parameter to be set by the user although this parameter is **not required** according to the spec. Could this be correct? Please see my previous post for an example.

**Comment by danielgtaylor** [comment]
@myrho I tried your example:

```sh
$ restish petstore find-pets-by-status -v
DEBUG: API loading took 10.93918ms
DEBUG: Configuration: map[app-name:restish config-directory:/Users/dan/.restish rsh-ca-cert: rsh-client-cert: rsh-client-key: rsh-filter: rsh-header:[] rsh-insecure:false rsh-no-cache:false rsh-no-paginate:false rsh-output-format:auto rsh-profile:default rsh-query:[] rsh-raw:false rsh-server: rsh-table:false rsh-verbose:true server-index:0]
DEBUG: Adding TLS configuration
DEBUG: Making request:
GET /api/v3/pet/findByStatus HTTP/1.1
Host: petstore3.swagger.io
Accept: application/cbor;q=0.9,application/msgpack;q=0.8,application/ion;q=0.6,application/json;q=0.5,application/yaml;q=0.5,text/*;q=0.2,*/*
Accept-Encoding: gzip, br
User-Agent: restish-dev


DEBUG: Got response from server in 374.257404ms:
HTTP/2.0 400 Bad Request
Content-Length: 30
Access-Control-Allow-Headers: Content-Type, api_key, Authorization
Access-Control-Allow-Methods: GET, POST, DELETE, PUT
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Disposition
Content-Type: application/json
Date: Wed, 13 Apr 2022 19:47:29 GMT
Server: Jetty(9.4.9.v20180320)

No status provided. Try again?
```

Restish does not require a status (the command runs fine without `--status`) and the request it generates does not include a status in the URL query. This seems correct to me, so I'm having trouble understanding where you think the bug is?

The service obviously responds with a `400 Bad Request` and saying no status was provided. Well that's surprising, because the server told us it is not required and has a default! This is a badly implemented server!

**Comment by myrho** [comment]
Ah, of course. That was my misconception. Thank you for sorting this out.
