### ISSUE TITLE
Comparison with curl and httpie

### ISSUE THREAD

**Issue by waldyrious** [danielgtaylor/restish#97]
It would be helpful for prospective adopters to see a direct comparison of features (or main stand-out differences) between `restish` and alternative tools like `curl` and [httpie](https://httpie.org).

For example, a comparison table like the ones shown by [delta](https://github.com/dandavison/delta/blob/master@%7B2022-04-13%7D/manual/src/features.md) or [zola](https://github.com/getzola/zola/blob/1f75738977e30fca70fcfe9bef8fbc546f22c887/README.md#comparisons-with-other-static-site-generators), or even a hello world comparison like what's done in the [Chain.jl README](https://github.com/jkrumbiegel/Chain.jl/blob/affd7f44d8e039afd533f239fd903b25137a6810/README.md), would be very helpful to encourage people to explore this tool further.

**Comment by danielgtaylor** [comment]
Please have a look at https://rest.sh/#/comparison and let me know if there is anything else I should add! Thanks for the idea :+1:

**Comment by waldyrious** [comment]
Oh wow, that is amazing! Awesome (and impressively fast) work! :clap:

I will just mention that I just recently learned about https://github.com/rs/curlie, and perhaps it could eventually be included as well. But the current documentation is already way more comprehensive than I expected! Thank you :)

**Comment by waldyrious** [comment]
Oh, by the way, I think it would be a good idea to link to the comparison table from the "[Why use this?](https://rest.sh/#/?id=why-use-this)" section of the main page, just to make it extra discoverable :)

**Comment by danielgtaylor** [comment]
Added a link in the "Why use this?" section in https://github.com/danielgtaylor/restish/pull/102
