### ISSUE TITLE
[Feature request] Adhere to freedesktop conventions (instead of ~/.restish)

### ISSUE THREAD

**Issue by pvonmoradi** [danielgtaylor/restish#98]
It would be nice if the project could follow [freedesktop](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) `XDG_DATA_DIR` instead of `$HOME/.restish` so home would not be cluttered.
I don't know GO, but it seems there is a module for this: https://github.com/adrg/xdg

**Comment by examosa** [comment]
As a temporary workaround, the environment variables `RESTISH_CONFIG_DIR` and `RESTISH_CACHE_DIR` can be set to enforce XDG conventions i.e.

```sh
# In $HOME/.profile, etc.
export RESTISH_CONFIG_DIR="${XDG_CONFIG_HOME}/restish" RESTISH_CACHE_DIR="${XDG_CACHE_HOME}/restish"
```

`~/.restish/apis.json` can be moved to the former and `~/.restish/{cache.json,responses/}` the latter.
