### ISSUE TITLE
`--rsh-raw` mode outputs large integers in scientific notation

### ISSUE THREAD

**Issue by pvonmoradi** [danielgtaylor/restish#99]
When `-r` mode is used, the integer array is converted to its corresponding scientific notation. 
Currently I'm using `printf "%.f"` to convert it back.

**Comment by danielgtaylor** [comment]
Currently this is using `fmt.Sprintf("%v", ...)`, see: https://github.com/danielgtaylor/restish/blob/main/cli/formatter.go#L268

May want to special case floats to use `%f` instead based on https://pkg.go.dev/fmt#hdr-Printing
